name: main

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  style:
    runs-on: ubuntu-latest
    container:
      image: wasmvm/wasmvm:ci
    steps:
      - uses: actions/checkout@v2
      - name: Check coding style
        run: ./scripts/style_check.sh
  build:
    runs-on: ubuntu-latest
    container:
      image: wasmvm/wasmvm:ci
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build
        run: mkdir build && cd build && cmake -G Ninja --config Release .. && ninja