name: main

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: wasmvm/wasmvm:ci
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: git submodule status third_party/wabt > .wabt_head
      - uses: actions/cache@v2
        with:
          path:
            ${{ github.workspace }}/build/third_party/wabt
          key: ${{ hashFiles('.wabt_head') }}
      - run: mkdir -p build && cd build && cmake -G Ninja --config Release .. && ninja
      - uses: actions/cache@v2
        with:
          path:
            ${{ github.workspace }}/build
          key: ${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    container:
      image: wasmvm/wasmvm:ci
    needs: build
    steps:
      - uses: actions/cache@v2
        with:
          path:
            ${{ github.workspace }}/build
          key: ${{ github.sha }}
      - name: Run CTest
        run: cd build && ctest